cache:
  directories:
  - $HOME/.composer/cache

language: php

matrix:
  include:
  - php: 7.2
  - php: nightly

  fast_finish: true

  allow_failures:
  - php: nightly

install:
  - chmod +x ./scripts/travis_install.sh && ./scripts/travis_install.sh

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist

script:
  - composer test
  - composer lint

notifications:
    slack: crazyfactory:Z3NJKlj5jdPOE1YrjPPyDPKb
